# ===============================

# SERVER CONFIG

# ===============================

server.port=${Server_Port}

# ===============================

# AWS RDS DATABASE CONFIG

# ===============================

spring.datasource.url=${DataSource_Url}
spring.datasource.username=${DataSource_UserName}
spring.datasource.password=${DataSource_Password}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================

# POSTGRESQL DIALECT

# ===============================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================

# JPA / HIBERNATE CONFIG

# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata


# ===============================

# LOGGING

# ===============================

logging.level.org.springframework=INFO
logging.level.com.webapp.cognitodemo=DEBUG


# ===============================

# AWS COGNITO Configs for Authentication and Authorisation

# ===============================

#IAM User having access policy attached for awscognito and S3 Credentials
aws.accessKey=${AWS_AccessKey}
aws.secretKey=${AWS_SecretKey}

aws.cognito.userPoolId=${AWS_Cognito_UserPoolId}
aws.cognito.clientId=${AWS_Cognito_ClientId}
aws.cognito.region=${AWS_Cognito_Region}
aws.cognito.clientSecret=${AWS_Cognito_ClientSecret}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${Aws_ResourseSercer_Jwt_Issuer_URL}

# ===============================

# AWS S3 bucket Configs for Files Storage

# ===============================

aws.s3.bucket-name=${Aws_S3_Bucket_Name}
aws.s3.region=${Aws_S3_Bucket_Region}

# ===============================

# SMTP Configs

# ===============================
spring.mail.host=${SMTP_Host}
spring.mail.port=${SMTP_Port}
spring.mail.username=${SMTP_UserName}
spring.mail.password=${SMTP_Password}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.devtools.restart.enabled=false

# ===============================
# SWAGGER / SPRINGDOC
# ===============================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true

# ===============================
# Multipart upload limits (PDFs + profile image)
# ===============================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=60MB

# ===============================
# #RazorPay Credentials
# ===============================

razorpay.key.id=${RazorPay_Key_ID}
razorpay.key.secret=${RazorPay_Key_Secret}

# ===============================
# Checking which filter is rejecting request
# ===============================

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.filter=TRACE
